version: "3.9"

services:
  trainer:
    build: .
    container_name: trainer
    volumes:
      - .:/workspace
    command: python train.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - MLFLOW_TRACKING_URI=file:/workspace/mlruns
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "5000:5000"  # for MLflow UI

  mlflow-ui:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow-server
    volumes:
      - ./mlruns:/mlruns
    ports:
      - "5001:5000"  # expose MLflow UI on localhost:5001
    environment:
      - MLFLOW_TRACKING_URI=file:/mlruns
